[package]
name = "firc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.1", features = ["derive"] }
firc_core = { path = "../core" }
firc_front = { path = "../frontend" }
